version: "3.7"
services:
  flask:
    container_name: flask
    build: ./flask
    ports:
      - 5000:5000

    depends_on:
      db:
        condition: service_healthy

    volumes:
      - ./flask/:/flask
    environment:
      TZ: Asia/Tokyo
      FLASK_ENV: "development" #デバッグモードON
      FLASK_APP: "app.py" #起動用アプリの設定
    command: flask run -h 0.0.0.0

  db:
    build: ./mysql
    platform: linux/amd64
    ports:
      - 3306:3306
    volumes:
      - ./mysql/db/data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${ROOT_PASS}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u$$MYSQL_USER -p$$MYSQL_PASSWORD
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 30s
    cap_add: # 追加
      - SYS_NICE
